### PR TITLE
Fix load_etext for etexts 1-9

### PR DESCRIPTION
**Pull request by hugovk**
Precondition, no cached etext no. 1: 
```bash
rm ~/gutenberg_data/text/1.txt.gz
```

With this code:
```python
from gutenberg.acquire import load_etext
text = load_etext(1)
print(text)[:200]
```
Results in:
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /etext90/when11.txt was not found on this server.</p>
```
With this PR, results in:
```txt


===========================================================

     NOTE:  This file combines the first two Project Gutenberg
     files, both of which were given the filenumber #1. There are


```
A similar thing happens for etexts 1-9.

Previously the URI for etexts 1-9 were special cases like:
http://www.gutenberg.lib.md.us/etext90/when11.txt

But now they're the like etexts>=10, like:
http://www.gutenberg.lib.md.us/0/1/1.txt

### CODE REVIEW

**Comment by hugovk** [comment]
The build failed due to unsupported Python 3.2, see https://github.com/c-w/Gutenberg/issues/49. The others passed.

**Comment by MasterOdin** [comment]
I'm glad to know they finally got rid of these stupid exceptions (completely in fact)! 👍 

However, I think it'd be possible to not even special case it by doing `str_etextno = str(etextno).zfill(2)` so:
```
    uri_root = r'http://www.gutenberg.lib.md.us'
    extensions = ('.txt', '-8.txt', '-0.txt')
    str_etextno = str(etextno).zfill(2)
    for extension in extensions:
        path = '/'.join(str_etextno[:len(str_etextno) - 1])
        uri = '{root}/{path}/{etextno}/{etextno}{extension}'.format(
            root=uri_root,
            path=path,
            etextno=str_etextno,
            extension=extension)
        response = requests.head(uri)
        if response.ok:
            return uri
    raise UnknownDownloadUriException
```

**Comment by hugovk** [comment]
Good idea to remove that special case too. That code offers:
http://www.gutenberg.lib.md.us/0/01/01.txt
http://www.gutenberg.lib.md.us/0/01/01-8.txt
http://www.gutenberg.lib.md.us/0/01/01-0.txt

When we want:
http://www.gutenberg.lib.md.us/0/1/1.txt

Here's an update that removes it in another way. Tested with precondition:
```bash
rm ~/gutenberg_data/text/*
```
And:
```python
from gutenberg.acquire import load_etext

for no in [1, 19, 15453]:
    print(no)
    text = load_etext(no)
    print(text)[:200]
```

Also temporarily put these in text.py:
```python
assert _etextno_to_uri_subdirectory(1) == "0/1"
assert _etextno_to_uri_subdirectory(19) == "1/19"
assert _etextno_to_uri_subdirectory(15453) == "1/5/4/5/15453"
```

**Comment by hugovk** [comment]
Merged with master and CI now passes (due to removed unsupported Python 3.2).

**Comment by sethwoodworth** [comment]
I tested this branch vs master and I agree that this fixes the special case.  One small comment about the existing test but otherwise this LGTM.  

@MasterOdin I'd be happy to review a pull request to refactor the method. But I'd first like to see better tests on the method.

Do you think that this [test comment](https://github.com/hugovk/Gutenberg/blob/166b661f66aa0039267a8c19c7d60a66a87d3496/tests/test_acquire.py#L38) should be updated where it says `oldstyle identifier`?

`tests/test_acquire.py`
```python
        testcases = (
            SampleMetaData.for_etextno(2701),   # newstyle identifier
            SampleMetaData.for_etextno(5),      # oldstyle identifier
            SampleMetaData.for_etextno(14287),  # unicode text
            SampleMetaData.for_etextno(23962)   # UTF-8 text
        )
```

**Comment by sethwoodworth** [comment]
And @hugovk how do you feel about squashing your commits before you merge?  I like it because it makes a nicer `git log`, but there is no convention in this repo AFAIK.

**Comment by hugovk** [comment]
@sethwoodworth Can do, or does this [merge option](https://github.com/blog/2141-squash-your-commits) help? 
 image

**Comment by sethwoodworth** [comment]
Squash and merge sounds great :+1:

**Comment by hugovk** [comment]
@sethwoodworth @MasterOdin Any more comments about this? Or are we good to squash and merge?

**Pull request merged**
