### PR TITLE
Avoid bare except

### LINKED ISSUE #92: Daily cron build failing: E722 do not use bare 'except'
For example:
```
0.54s$ flake8 gutenberg
gutenberg/acquire/metadata.py:66:9: E722 do not use bare except'
```
https://travis-ci.org/c-w/gutenberg/builds/294364238

### PR DESCRIPTION
**Pull request by c-w**
Fixes #92

### CODE REVIEW

**Comment by hugovk** [comment]
I guess the general idea of the warning is to catch more specific exceptions, but it can be hard to know what the intention was with old code so this is fine. In the future let's be more specific with new ones.

**Comment by MasterOdin** [comment]
For the ones that catch `Exception` and then just immediately reraise, is there really even a point to having them?

**Comment by hugovk** [comment]
They don't do much, do they? Let's remove them!

**Comment by hugovk** [comment]
See PR https://github.com/c-w/gutenberg/pull/94.

**Pull request merged**
