### PR TITLE
Add additional TEXT_START_MARKERS

### PR DESCRIPTION
**Pull request by ageitgey**
Thanks for creating this module!

I was trying to create a clean dataset of the entire PG corpus. These are the additional TEXT_START_MARKERS needed to do that. I figured this might be useful to others as well.

### CODE REVIEW

**Comment by ageitgey** [comment]
I'll take a look at fixing the tests a little later today.

**Comment by c-w** [comment]
Thanks for opening this pull request. Please make sure to fix the tests (and maybe even add a few more) and I'll merge it.

**Comment by c-w** [comment]
@ageitgey: Are you still interested in landing this PR?

**Comment by ageitgey** [comment]
Sorry, I forgot about this PR from last year. Feel free to close it. Thanks.

**Pull request closed without merging**
