### PR TITLE
Move to pypi RDFlib-SQLAlchemy dependency (rebased)

### PR DESCRIPTION
**Pull request by sethwoodworth**
A rebased version of #41 which can be merged if it passes travis.

### CODE REVIEW

**Comment by sethwoodworth** [comment]
Well, that didn't work. Will return to this after reviewing the other open PRs.

**Comment by sethwoodworth** [comment]
When I run this locally with `nosetests`, this works fine.  When I run this locally with our travis-ci config command `coverage run --source=gutenberg -m nose`, I get the same errors as travis.  I'm going to experiment with versions of `nosetests --with-coverage`. Ping @hugovk

**Comment by hugovk** [comment]
The failure is:
```
ERROR: test_delete (tests.test_metadata_cache.TestSqlite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/c-w/Gutenberg/tests/test_metadata_cache.py", line 107, in setUp
    self.cache = SqliteMetadataCache(self.local_storage)
  File "/home/travis/build/c-w/Gutenberg/gutenberg/acquire/metadata.py", line 205, in __init__
    store = plugin.get('SQLAlchemy', Store)(identifier=_DB_IDENTIFIER)
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/rdflib/plugin.py", line 103, in get
    "No plugin registered for (%s, %s)" % (name, kind))
PluginException: No plugin registered for (SQLAlchemy, <class 'rdflib.store.Store'>)
```

---

This https://github.com/RDFLib/rdflib-sqlalchemy/commit/8f8f17f61aeedf4ca38290d160277f687db6e4c3 commit passes (which is just five commits after the https://github.com/RDFLib/rdflib-sqlalchemy/commit/20fbf1fbbdbc53917bfd7554f38d22d08e71e225 in requirements.pip):

` pip uninstall rdflib-sqlalchemy -y && pip install git+https://github.com/RDFLib/rdflib-sqlalchemy.git@8f8f17f61aeedf4ca38290d160277f687db6e4c3 && coverage run --source=gutenberg -m nose -x`

The next commit https://github.com/RDFLib/rdflib-sqlalchemy/commit/ccec3517b69c4abda40e72a22f4cb65b5b33ba11 fails:

`pip uninstall rdflib-sqlalchemy -y && pip install git+https://github.com/RDFLib/rdflib-sqlalchemy.git@ccec3517b69c4abda40e72a22f4cb65b5b33ba11 && coverage run --source=gutenberg -m nose -x`

---

That commit includes `'SQLAlchemy = rdflib_sqlalchemy.SQLAlchemy:SQLAlchemy',` being commented out:

```python
    entry_points={
        'rdf.plugins.store': [
            # 'SQLAlchemy = rdflib_sqlalchemy.SQLAlchemy:SQLAlchemy',
            # 'SQLAlchemyBase = rdflib_sqlalchemy.SQLAlchemyBase:SQLAlchemy',
        ],
    },
```
https://github.com/RDFLib/rdflib-sqlalchemy/commit/ccec3517b69c4abda40e72a22f4cb65b5b33ba11#diff-2eeaed663bd0d25b7e608891384b7298R113

**Comment by MasterOdin** [comment]
They basically changed it from auto-registering a couple plugins to putting it on the end user, which probably makes sense for them.

I believe, we need to just do something like `plugin.register("SQLAlchemy")` after our imports and it should work.

**Comment by MasterOdin** [comment]
Well, fixed one error, get another one. Looks like registering the plugin for SQLAlchemy causes us to not change SQLite caches per test.

**Comment by c-w** [comment]
@sethwoodworth @MasterOdin @hugovk: I finally found some time to look into this. The latest rdflib-sqlalchemy version from PyPI now works with this project. Could you please take a look and let me know what you think?

**Comment by MasterOdin** [comment]
After merging this in, we should then be able to release to pypi directly via git tags instead of having to worry about going through the pypi cli.

**Pull request merged**
